import {Ingredient} from "../components/DataTable/DataTableState";


export const ingredientsList: Ingredient[] = [
    {
        index: 1,
        name: 'Śruta jęczmienna',
        converters: {
            sm: 880,
            mj: 11.85,
            białko: 111,
            lizyna: 3.88,
            metionina: 1.8,
            tryptofan: 1.3,
            arginina: 5.1,
            włókno: 48,
            ca: 0.4,
            p: 3.7,
            na: 0.1,
        }
    },
    {
        index: 2,
        name: 'Śruta pszenna',
        converters: {
            sm: 880,
            mj: 12.85,
            białko: 118,
            lizyna: 3.54,
            metionina: 1.8,
            tryptofan: 1.3,
            arginina: 5.3,
            włókno: 29,
            ca: 0.7,
            p: 3.7,
            na: 0.1,
        }
    },
    {
        index: 3,
        name: 'Śruta pszenżytnia',
        converters: {
            sm: 880,
            mj: 12.6,
            białko: 120,
            lizyna: 3.8,
            metionina: 1.8,
            tryptofan: 1.2,
            arginina: 5.3,
            włókno: 24,
            ca: 0.4,
            p: 3.7,
            na: 0.1,
        }
    },
    {
        index: 4,
        name: 'Śruta kukurydziana',
        converters: {
            sm: 880,
            mj: 13.75,
            białko: 93,
            lizyna: 2.61,
            metionina: 1.8,
            tryptofan: 0.6,
            arginina: 3.9,
            włókno: 29,
            ca: 0.4,
            p: 2.6,
            na: 0.2,
        }
    },
    {
        index: 5,
        name: 'Śruta z owsa',
        converters: {
            sm: 880,
            mj: 10.75,
            białko: 114,
            lizyna: 4.57,
            metionina: 1.8,
            tryptofan: 1.2,
            arginina: 6.8,
            włókno: 89,
            ca: 0.7,
            p: 3.7,
            na: 0.6,
        }
    },
    {
        index: 6,
        name: 'Otręby pszenne',
        converters: {
            sm: 880,
            mj: 8.5,
            białko: 143,
            lizyna: 5.74,
            metionina: 2.7,
            tryptofan: 2.6,
            arginina: 9.8,
            włókno: 63,
            ca: 1.1,
            p: 10.2,
            na: 0.3,
        }
    },
    {
        index: 7,
        name: 'Śruta z bobiku',
        converters: {
            sm: 880,
            mj: 10.1,
            białko: 268,
            lizyna: 17.7,
            metionina: 1.9,
            tryptofan: 2.3,
            arginina: 23.9,
            włókno: 73,
            ca: 1.2,
            p: 5.3,
            na: 0.1,
        }
    },
    {
        index: 8,
        name: 'Śruta z łubinu żółtego',
        converters: {
            sm: 880,
            mj: 8.3,
            białko: 390,
            lizyna: 19.5,
            metionina: 2.5,
            tryptofan: 3.1,
            arginina: 43.1,
            włókno: 135,
            ca: 2.4,
            p: 7.1,
            na: 0.1,
        }
    },
    {
        index: 9,
        name: 'Śruta z grochu',
        converters: {
            sm: 880,
            mj: 10.35,
            białko: 209,
            lizyna: 15.6,
            metionina: 2,
            tryptofan: 2.2,
            arginina: 18.3,
            włókno: 60,
            ca: 0.8,
            p: 3.6,
            na: 0.1,

        }
    },
    {
        index: 10,
        name: 'Pełnotłusta śruta z rzepaku',
        converters: {
            sm: 930,
            mj: 18.85,
            białko: 192,
            lizyna: 12.4,
            metionina: 4,
            tryptofan: 2.8,
            arginina: 13.6,
            włókno: 101,
            ca: 3.4,
            p: 7,
            na: 0.2,
        }
    },
    {
        index: 11,
        name: 'Pełnotłusta soja ekstrudowana',
        converters: {
            sm: 930,
            mj: 13.55,
            białko: 350,
            lizyna: 20.7,
            metionina: 4.7,
            tryptofan: 4.6,
            arginina: 24.8,
            włókno: 64,
            ca: 2.6,
            p: 6.2,
            na: 0.3,
        }
    },
    {
        index: 12,
        name: 'Śruta poekstrakcyjna rzepakowa',
        converters: {
            sm: 880,
            mj: 7.45,
            białko: 340,
            lizyna: 18.2,
            metionina: 6.9,
            tryptofan: 4.5,
            arginina: 20.4,
            włókno: 112,
            ca: 6.6,
            p: 11.2,
            na: 0.4,
        }
    },
    {
        index: 13,
        name: 'Śruta poekstrakcyjna sojowa(42-46)',
        converters: {
            sm: 880,
            mj: 8.6,
            białko: 420,
            lizyna: 26.1,
            metionina: 5.6,
            tryptofan: 5.2,
            arginina: 34.5,
            włókno: 102,
            ca: 3.5,
            p: 5.4,
            na: 0.4,
        }
    },
    {
        index: 14,
        name: 'Śruta poekstrakcyjna sojowa(>46)',
        converters: {
            sm: 880,
            mj: 9,
            białko: 466,
            lizyna: 27.5,
            metionina: 6.5,
            tryptofan: 6.2,
            arginina: 35.5,
            włókno: 78,
            ca: 3.5,
            p: 5.4,
            na: 0.4,
        }
    },
    {
        index: 15,
        name: 'Śruta poekstrakcyjna słonecznikowa(obł)',
        converters: {
            sm: 880,
            mj: 6.5,
            białko: 340,
            lizyna: 12.1,
            metionina: 7.4,
            tryptofan: 4.2,
            arginina: 27.5,
            włókno: 175,
            ca: 3.2,
            p: 8.8,
            na: 0.2,
        }
    },
    {
        index: 16,
        name: 'DDGS kukurydziany',
        converters: {
            sm: 880,
            mj: 10.69,
            białko: 260,
            lizyna: 5.1,
            metionina: 4.7,
            tryptofan: 3.8,
            arginina: 11.6,
            włókno: 77,
            ca: 2.1,
            p: 8.4,
            na: 5.4,
        }
    },
    {
        index: 16,
        name: 'Drożdże pastewne',
        converters: {
            sm: 900,
            mj: 10.3,
            białko: 426,
            lizyna: 29.4,
            metionina: 6.4,
            tryptofan: 5,
            arginina: 18.9,
            włókno: 65,
            ca: 5,
            p: 14.3,
            na: 0.1,
        }
    },
    {
        index: 17,
        name: 'Mleko odtłuszczone',
        converters: {
            sm: 930,
            mj: 9.85,
            białko: 327,
            lizyna: 26.1,
            metionina: 8.8,
            tryptofan: 4.5,
            arginina: 11.6,
            włókno: 0,
            ca: 12.4,
            p:  8.8,
            na: 5,
        }
    },
    {
        index: 18,
        name: 'Serwatka',
        converters: {
            sm: 930,
            mj: 8,
            białko: 122,
            lizyna: 9.5,
            metionina: 1.8,
            tryptofan: 1.7,
            arginina: 2.9,
            włókno: 0,
            ca: 5.1,
            p: 6,
            na: 6.5,
        }
    },
    {
        index: 19,
        name: 'Susz z lucerny',
        converters: {
            sm: 910,
            mj: 5.45,
            białko: 202,
            lizyna: 9.3,
            metionina: 2.9,
            tryptofan: 3.4,
            arginina: 8.1,
            włókno: 206,
            ca: 13.2,
            p: 3.1,
            na: 0.8,
        }
    },
    {
        index: 20,
        name: 'Olej',
        converters: {
            sm: 1000,
            mj: 37.65,
            białko: 0,
            lizyna: 0,
            metionina: 0,
            tryptofan: 0,
            arginina: 0,
            włókno: 0,
            ca: 0,
            p: 0,
            na: 0,
        }
    },
    {
        index: 21,
        name: 'Mączka rybna(65% b.o.)',
        converters: {
            sm: 910,
            mj: 12.2,
            białko: 647,
            lizyna: 49.3,
            metionina: 20.1,
            tryptofan: 7.4,
            arginina: 37.4,
            włókno: 0,
            ca: 33.2,
            p: 27.6,
            na: 11.3,
        }
    },
    {
        index: 22,
        name: 'Premix',
        converters: {
            sm: 900,
            mj: 0,
            białko: 0,
            lizyna: 70,
            metionina: 0,
            tryptofan: 0,
            arginina: 0,
            włókno: 0,
            ca: 0,
            p: 0,
            na: 0,
        }
    },


];