export const headerData = {
    name: 'nazwa',
    share: '%',
    price: 'Cena PLN',
    sm: 'S.M.',
    mj: 'MJ_EM',
    białko: 'Białko ogólne(g)',
    lizyna: 'Lizyna(g)',
    metionina: 'Metionina(g)',
    tryptofan: 'Tryptofan(g)',
    arginina: 'Arginina(g)',
    włókno: 'Włókna(g)',
    ca: 'Ca(g)',
    p: 'P ogólny(g)',
    na: 'Na(g)',
};

// export enum basicKeys {
//     name,
//     share,
//     price,
//     sm,
//     mj,
//     białko,
//     lizyna,
//     metionina,
//     tryptofan,
//     arginina,
//     włókno,
//     ca,
//     p,
//     na,
// };
