
export const recommendedDosesDucks = [
    {
        name: 'pekin 1-3tyg.',
        energia: '11,9',
        białko: '210-230',
        lizyna: '10',
        metionina: '5',
        tryptofan: '-',
        arginina: '-',
        włókno: '-',
        Ca: '10-12',
        P: '4',
        Na: '1,4-1,8',
    },
    {
        name: 'pekin 4-10tyg.',
        energia: '11,9',
        białko: '175-190',
        lizyna: '8',
        metionina: '4',
        tryptofan: '-',
        arginina: '-',
        włókno: '-',
        Ca: '9-10',
        P: '3.5',
        Na: '1,4-1,8',
    },
    {
        name: 'pekin 11-21tyg',
        energia: '11,3',
        białko: '145-160',
        lizyna: '7',
        metionina: '3',
        tryptofan: '-',
        arginina: '-',
        włókno: '-',
        Ca: '9-10',
        P: '3,5',
        Na: '1,4-1,8',
    },
    {
        name: 'pekin 22-25tyg.',
        energia: '11,1',
        białko: '170-180',
        lizyna: '9,4',
        metionina: '5',
        tryptofan: '-',
        arginina: '-',
        włókno: '-',
        Ca: '30',
        P: '4',
        Na: '1,4-1,8',
    },
    {
        name: 'pekin nioska',
        energia: '11,3',
        białko: '195-205',
        lizyna: '9,5',
        metionina: '5',
        tryptofan: '-',
        arginina: '-',
        włókno: '-',
        Ca: '32',
        P: '4',
        Na: '1.8',
    },
]