
export const recommendedDosesData = [
    {
        name: 'brojler 1-10dni',
        energia: '12,5-12,7',
        białko: '220-230',
        lizyna: '13.8',
        metionina: '5.3',
        tryptofan: '-',
        arginina: '-',
        włókno: 'max 40',
        Ca: '9.6',
        P: '4.7',
        Na: '1.5-2',
    },
    {
        name: 'brojler 11-24dni',
        energia: '12,9-13',
        białko: '200-220',
        lizyna: '12.5',
        metionina: '5.1',
        tryptofan: '-',
        arginina: '-',
        włókno: 'max 40',
        Ca: '8.8',
        P: '4.7',
        Na: '1.5-2',
    },
    {
        name: 'brojler 25-35dni',
        energia: '13,3-13,4',
        białko: '190-200',
        lizyna: '11.3',
        metionina: '4.6',
        tryptofan: '-',
        arginina: '-',
        włókno: 'max 40',
        Ca: '8',
        P: '5',
        Na: '1.5-2',
    },
    {
        name: 'brojler 36-42dni',
        energia: '13,4-13,5',
        białko: '180-190',
        lizyna: '10.5',
        metionina: '4.3',
        tryptofan: '-',
        arginina: '-',
        włókno: 'max 40',
        Ca: '7.6',
        P: '5',
        Na: '1.5-2',
    },
    {
        name: 'nioska I',
        energia: '11,5-11,7',
        białko: '160-175',
        lizyna: '8.1',
        metionina: '4',
        tryptofan: '-',
        arginina: '-',
        włókno: 'max 55',
        Ca: '36',
        P: '4.5',
        Na: '1.5-2',
    },
    {
        name: 'nioska II',
        energia: '11,1-11,5',
        białko: '150-170',
        lizyna: '7.8',
        metionina: '3.8',
        tryptofan: '-',
        arginina: '-',
        włókno: 'max 55',
        Ca: '38',
        P: '4.5',
        Na: '1.5-2',
    },
]