
export const recommendedDosesNumididae = [
    {
        name: 'brojler 1-3 tyg.',
        energia: '12,5',
        białko: '240',
        lizyna: '13.5',
        metionina: '6.0',
        tryptofan: '3.0',
        arginina: '-',
        włókno: 'max 30',
        Ca: '12',
        P: '5.5',
        Na: '1.7',
    },
    {
        name: 'brojler 4-8 tyg.',
        energia: '13,4',
        białko: '230',
        lizyna: '13.0',
        metionina: '5.5',
        tryptofan: '2.5',
        arginina: '-',
        włókno: 'max 40',
        Ca: '10',
        P: '4.5',
        Na: '1.7',
    },
    {
        name: 'brojler 9tyg-do uboju',
        energia: '13,4',
        białko: '200',
        lizyna: '10.5',
        metionina: '4.5',
        tryptofan: '2.0',
        arginina: '-',
        włókno: 'max 45',
        Ca: '9',
        P: '4',
        Na: '1.7',
    },
    {
        name: 'rosnące 1-3 tyg.',
        energia: '12,3',
        białko: '220',
        lizyna: '12,5',
        metionina: '5,5',
        tryptofan: '2,5',
        arginina: '-',
        włókno: 'max 35',
        Ca: '11',
        P: '5.5',
        Na: '1.7',
    },
    {
        name: 'rosnące 4-8 tyg.',
        energia: '11,7',
        białko: '200',
        lizyna: '12,5',
        metionina: '5',
        tryptofan: '2',
        arginina: '-',
        włókno: 'max 40',
        Ca: '10',
        P: '5',
        Na: '1.7',
    },
    {
        name: 'rosnące 9-13 tyg.',
        energia: '11,7',
        białko: '160',
        lizyna: '8,5',
        metionina: '3,5',
        tryptofan: '1,5',
        arginina: '-',
        włókno: 'max 65',
        Ca: '9',
        P: '4,5',
        Na: '1.7',
    },
    {
        name: 'dorosłe niosące',
        energia: '11,9',
        białko: '170',
        lizyna: '9',
        metionina: '4',
        tryptofan: '2',
        arginina: '-',
        włókno: 'max 60',
        Ca: '38',
        P: '6.5',
        Na: '1.7',
    },
    {
        name: 'dorosłe nie niosące',
        energia: '11,3',
        białko: '130',
        lizyna: '6',
        metionina: '3',
        tryptofan: '1.5',
        arginina: '-',
        włókno: 'max 80',
        Ca: '10',
        P: '3.5',
        Na: '1.7',
    },
]