
export const recommendedDosesNumididae = [
    {
        name: 'brojler 1-3 tyg.',
        energia: '12,5',
        białko: '240',
        lizyna: '13.5',
        metionina: '6.0',
        tryptofan: '3.0',
        arginina: '-',
        włókno: 'max 30',
        Ca: '12',
        P: '5.5',
        Na: '1.7',
    },
    {
        name: 'brojler 4-8 tyg.',
        energia: '13,4',
        białko: '230',
        lizyna: '13.0',
        metionina: '5.5',
        tryptofan: '2.5',
        arginina: '-',
        włókno: 'max 40',
        Ca: '10',
        P: '4.5',
        Na: '1.7',
    },
    {
        name: 'brojler 9tyg-do uboju',
        energia: '13,4',
        białko: '200',
        lizyna: '10.5',
        metionina: '4.5',
        tryptofan: '2.0',
        arginina: '-',
        włókno: 'max 45',
        Ca: '9',
        P: '4',
        Na: '1.7',
    },
    {
        name: 'nioska I',
        energia: '12.3 - 11.7',
        białko: '160-220',
        lizyna: '12.5-8.5',
        metionina: '3.5-5.5',
        tryptofan: '1.5-2.5',
        arginina: '-',
        włókno: 'max 65',
        Ca: '11',
        P: '5.5',
        Na: '1.7',
    },
    {
        name: 'nioska II',
        energia: '11,9-11,3',
        białko: '130-170',
        lizyna: '6-9',
        metionina: '3-4',
        tryptofan: '1.5-2',
        arginina: '-',
        włókno: 'max 80',
        Ca: '10',
        P: '6.5',
        Na: '1.6',
    },
]